[Version]
Class=IEXPRESS
SEDVersion=3

[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=DOCFILL PRO instalado com sucesso.
TargetName=C:\Users\estagiario1\Nova pasta\DocFillPro\dist_installer\DOCFILL_PRO_Setup.exe
FriendlyName=DOCFILL PRO Setup
AppLaunched=install_docfillpro.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles

[SourceFiles]
SourceFiles0=C:\Users\estagiario1\Nova pasta\DocFillPro\installer\staging\

[SourceFiles0]
%FILE0%=
%FILE1%=

[Strings]
FILE0="DOCFILL_PRO.exe"
FILE1="install_docfillpro.cmd"
